# Generated by Django 6.0.3 on 2026-03-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("CP1", "CP1"),
                            ("CP2", "CP2"),
                            ("CE1", "CE1"),
                            ("CE2", "CE2"),
                            ("CM1", "CM1"),
                            ("CM2", "CM2"),
                            ("6eme", "6ème"),
                            ("5eme", "5ème"),
                            ("4eme", "4ème"),
                            ("3eme", "3ème"),
                            ("2nde", "2nde"),
                            ("1ere", "1ère"),
                            ("Tle", "Terminale"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(default="2025-2026", max_length=10),
                ),
                ("effectif_max", models.IntegerField(default=45)),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["niveau", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("coefficient", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(blank=True, max_length=100)),
                ("nom_parent", models.CharField(blank=True, max_length=200)),
                ("telephone_parent", models.CharField(blank=True, max_length=20)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "classe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eleves",
                        to="eleves.classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Professeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("date_recrutement", models.DateField(blank=True, null=True)),
                (
                    "matieres",
                    models.ManyToManyField(
                        related_name="professeurs", to="eleves.matiere"
                    ),
                ),
            ],
            options={
                "verbose_name": "Professeur",
                "verbose_name_plural": "Professeurs",
                "ordering": ["nom"],
            },
        ),
    ]
