# Generated by Django 6.0.3 on 2026-03-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eleves", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "trimestre",
                    models.IntegerField(
                        choices=[
                            (1, "Premier trimestre"),
                            (2, "Deuxième trimestre"),
                            (3, "Troisième trimestre"),
                        ]
                    ),
                ),
                (
                    "type_note",
                    models.CharField(
                        choices=[
                            ("devoir", "Devoir"),
                            ("composition", "Composition"),
                            ("interrogation", "Interrogation"),
                        ],
                        default="devoir",
                        max_length=15,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("date_saisie", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="eleves.matiere",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="eleves.professeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["-date_saisie"],
            },
        ),
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trimestre",
                    models.IntegerField(
                        choices=[
                            (1, "Premier trimestre"),
                            (2, "Deuxième trimestre"),
                            (3, "Troisième trimestre"),
                        ]
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(default="2025-2026", max_length=10),
                ),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("rang", models.IntegerField(blank=True, null=True)),
                ("appreciation", models.TextField(blank=True)),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eleves.classe"
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins",
                        to="eleves.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulletin",
                "verbose_name_plural": "Bulletins",
                "ordering": ["-date_generation"],
                "unique_together": {("eleve", "trimestre", "annee_scolaire")},
            },
        ),
    ]
